export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const HASTAG_CATEGORY = "HASTAG_CATEGORY";

export const SELECT_NEW_POSTS = "SELECT_NEW_POSTS";
export const SELECT_POSTS_RECENT = "SELECT_POSTS_RECENT";
export const SELECT_POSTS_TALK = "SELECT_POSTS_TALK";
export const SELECT_POSTS_DEV = "SELECT_POSTS_DEV";
export const SELECT_POSTS_TECH = "SELECT_POSTS_TECH";
export const SELECT_POSTS_READ = "SELECT_POSTS_READ";
export const SELECT_POSTS_RANDOM = "SELECT_POSTS_RANDOM";
export const SELECT_POSTS_VIEWS = "SELECT_POSTS_VIEWS";
export const SELECT_POSTS_ONE = "SELECT_POSTS_ONE";
export const SELECT_POSTS_CATEGORY = "SELECT_POSTS_CATEGORY";